version: '3.1'
services:
  backend:
    build: ./backend
    ports:
      - "${SERVER_PORT}:8000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    hostname: mongo,
    restart: always
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    # command: ["--auth"]
    env_file:
      - .env
volumes:
  mongodb_data: