version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "${SERVER_PORT}:8000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    ports:
      - "${MONGODP_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: